[build]
  command = "gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
  from = "/admin/*"
  to = "https://ghost.mjsalmeron.com/ghost/:splat"
  status = 200
  force = true
